
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team01-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"Elaine-Joke-Controller","number":22,"title":"Add Joke Controller and Controller Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-2/pull/22"},{"author":{"id":"U_kgDOBdC7MQ","is_bot":false,"login":"michaelw1985","name":"Michael W"},"headRefName":"michael-Tides","number":21,"title":"Add Tides Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-2/pull/21"},{"author":{"id":"U_kgDOBXc-yA","is_bot":false,"login":"nguyenliliana","name":""},"headRefName":"Liliana-PublicHoliday-Controller","number":20,"title":"Liliana public holiday controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-2/pull/20"}]
