
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-7pm-2
owner: ucsb-cs156-w24
repo_name: team01-w24-7pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjE1ODMzOTY4","is_bot":false,"login":"ashton-wong","name":"Ashton Wong"},"headRefName":"Ashton-University-Controller","number":31,"title":"Add University Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-2/pull/31"},{"author":{"id":"MDQ6VXNlcjUzMTg4OTY4","is_bot":false,"login":"elaineeeho","name":"Elaine Ho"},"headRefName":"Elaine-HomeController","number":23,"title":"Made changes to Home Controller ","url":"https://github.com/ucsb-cs156-w24/team01-w24-7pm-2/pull/23"}]
